name = "openbox-radar-poller"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[triggers]
crons = ["*/10 * * * *"]

[vars]
CRON_SHARED_SECRET = "change_me"
INGEST_URL = "https://your-domain.example/api/ingest"
