name = "openbox-radar-poller"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[triggers]
crons = ["*/10 * * * *"]

[vars]
CRON_SHARED_SECRET = "JB0uSHbUchIJ8iYpWKPQTk3Lqzcl332o4HWZNNKgKbzoXlS4dvy6bgZd+3bRymU4"
INGEST_URL = "http://localhost:3000/api/ingest"
USE_REAL_MICROCENTER = "1"
