name = "openbox-radar-poller"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[triggers]
crons = ["*/5 * * * *"]

[observability.logs]
enabled = true


[vars]

# Point to your local Next dev server ingest endpoint
# If your Next runs on :3001, change to http://localhost:3001/api/ingest
INGEST_URL = "https://openboxradar.com/api/ingest"
USE_REAL_MICROCENTER = "1"
USE_REAL_BESTBUY = "1"
USE_REAL_NEWEGG = "0"
ALLOW_DEV_STUBS = "0"
# Provide one of the following when USE_REAL_BESTBUY=1
# BESTBUY_SKUS can be a comma-separated list like: 1234567,7654321
BESTBUY_SKUS = ""
# Or use a category id like abcat0502000 (e.g., Laptops)
BESTBUY_CATEGORY = "abcat0502000"
# Optional page size for category queries
BESTBUY_PAGE_SIZE = "30"

# Set your key via env/secret in real deployments. Do not commit secrets.
# Do NOT set secrets here; use `wrangler secret put` for sensitive values like CRON_SHARED_SECRET and BESTBUY_API_KEY

# Alerts (scaffold)
ENABLE_ALERTS = "1"
ALERTS_BATCH_SIZE = "500"
# RESEND_API_KEY may be provided as a secret if sending from worker

# Best Buy store enrichment
ENABLE_BB_ENRICHMENT = "0"
BB_ENRICHMENT_TTL_MIN = "30"
BB_ENRICHMENT_FAIL_TTL_MIN = "10"
BB_MAX_ENRICH_RPS = "2"
